### ISSUE TITLE
standalone application and we are unable to locate the .NET Core SDK

### ISSUE THREAD

**Issue by lpt9** [agracio/electron-edge-js-quick-start#11]
Dear agracio,
     I downloaded the electron-edge-js-quick-start project, and after running it, the console will get the following error, indicating that.net is not installed, but it has been installed locally:
 `Error: This is not a published, standalone application and we are unable to locate the .NET Core SDK.  Please make sure that it is installed; see http://microsoft.com/net/core for more details.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\work\project\project_code_study\electron-edge-js-quick-start\node_modules\electron-edge-js\lib\edge.js:66:10)
    at Object.<anonymous> (D:\work\project\project_code_study\electron-edge-js-quick-start\node_modules\electron-edge-js\lib\edge.js:195:3)`

![图片](https://user-images.githubusercontent.com/45647323/137295563-6fb0a3c6-6718-4e55-9fce-18be48f5b851.png)
![图片](https://user-images.githubusercontent.com/45647323/137295626-8826e615-8bbd-4e79-a895-7114517ce08d.png)

**Comment by agracio** [comment]
For packaging standalone application take a look at this portion in readme : [Packaging standalone .NET Core app](https://github.com/agracio/electron-edge-js?tab=readme-ov-file#packaging-standalone-net-core-app)
