### ISSUE TITLE
Windows 10 Error

### ISSUE THREAD

**Issue by rfedericoni** [agracio/electron-edge-js-quick-start#9]
Hi,
all script are installed without error but in execution I receive this errore in electron app:
Error
__proto__
:
Error: Call to coreclr_create_delegate() for G failed with a return code of 0x80070002. at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20) at Object.Module._extensions..node (module.js:671:18) at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20) at Module.load (module.js:561:32) at tryModuleLoad (module.js:504:12) at Function.Module._load (module.js:496:3) at Module.require (module.js:586:17) at require (internal/module.js:11:18) at Object.<anonymous> (C:\Users\r.federiconi\Documents\Develop\Electron-Edge\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:57:10) at Object.<anonymous> (C:\Users\r.federiconi\Documents\Develop\Electron-Edge\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:186:3)
message
:
"Call to coreclr_create_delegate() for G failed with a return code of 0x80070002."
stack
:
"Error: Call to coreclr_create_delegate() for G failed with a return code of 0x80070002.↵    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)↵    at Object.Module._extensions..node (module.js:671:18)↵    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)↵    at Module.load (module.js:561:32)↵    at tryModuleLoad (module.js:504:12)↵    at Function.Module._load (module.js:496:3)↵    at Module.require (module.js:586:17)↵    at require (internal/module.js:11:18)↵    at Object.<anonymous> (C:\Users\r.federiconi\Documents\Develop\Electron-Edge\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:57:10)↵    at Object.<anonymous> (C:\Users\r.federiconi\Documents\Develop\Electron-Edge\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:186:3)"
__proto__
:
Object
![2021-01-21_165551](https://user-images.githubusercontent.com/5476720/105376079-a5241b00-5c09-11eb-9445-064a9ff5cd09.png)

**Comment by rfedericoni** [comment]
Solved by modifing the EdgeJs.dll path Dependency in the QuickStart.Core project file
